base_path: '~/.lidtk'
artifacts_path: '~/.lidtk/artifacts'
lang_dir_path: '~/.lidtk/lang/*.pickle'
labels_path: '~/.lidtk/data/labels.csv'
x_train_path: '~/.lidtk/data/x_train.txt'
y_train_path: '~/.lidtk/data/y_train.txt'
x_test_path: '~/.lidtk/data/x_test.txt'
y_test_path: '~/.lidtk/data/y_test.txt'
train_xs_pickle_path: '~/.lidtk/artifacts/data/char_features_{}_{}'
feature_extractor_path: '~/.lidtk/artifacts/features/char_extractor_{}.pickle'
LOGGING:
  version: 1
  disable_existing_loggers: False
  formatters:
      simple:
          format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  handlers:
      console:
          class: logging.StreamHandler
          level: DEBUG
          formatter: simple
          stream: ext://sys.stdout

      info_file_handler:
          class: logging.handlers.RotatingFileHandler
          level: INFO
          formatter: simple
          filename: lidtk.info.log
          maxBytes: 10485760 # 10MB
          backupCount: 20
          encoding: utf8

      error_file_handler:
          class: logging.handlers.RotatingFileHandler
          level: ERROR
          formatter: simple
          filename: lidtk.errors.log
          maxBytes: 10485760 # 10MB
          backupCount: 20
          encoding: utf8

  loggers:
      my_module:
          level: ERROR
          handlers: [console]
          propagate: no

  root:
      level: DEBUG
      handlers: [console, info_file_handler, error_file_handler]